# Generated by Django 4.2.11 on 2026-09-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mulenode',
            name='node_type',
            field=models.CharField(choices=[('VICTIM', 'Victim Account'), ('LAYER_1', 'Layer 1 Mule Account'), ('LAYER_2', 'Layer 2 Mule Account'), ('LAYER_3', 'Layer 3 Mule Account'), ('CASHOUT', 'Terminal Cash-Out Account'), ('CONFIRMED_MULE', 'Confirmed Multi-Case Mule Account'), ('UNKNOWN', 'Unknown Account')], default='UNKNOWN', max_length=20),
        ),
    ]
