# Generated by Django 4.2.11 on 2026-09-25 11:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('CCTV_REQUEST', 'Section 91 CCTV Preservation Notice'), ('CCTV_FOOTAGE', 'ATM Kiosk CCTV Footage'), ('TRANSACTION_PROOF', 'Victim Transaction Proof / UTR Receipt'), ('BANK_STATEMENT', 'Bank Statement Excerpt'), ('SEIZURE_MEMO', 'On-Scene Seizure Memo / Panchnama'), ('OTHER', 'Other Documentation')], default='TRANSACTION_PROOF', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='evidence/%Y/%m/%d/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('sha256_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('REQUEST_ISSUED', 'Notice Issued / Pending'), ('RECEIVED', 'Evidence Received'), ('SECURED', 'Secured & Cryptographically Sealed')], default='SECURED', max_length=50)),
                ('atm_id', models.CharField(blank=True, max_length=100)),
                ('atm_address', models.TextField(blank=True)),
                ('target_bank', models.CharField(blank=True, max_length=100)),
                ('time_window_start', models.DateTimeField(blank=True, null=True)),
                ('time_window_end', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.CharField(default='Cyber Cell Duty Officer', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='complaints.complaint')),
            ],
            options={
                'db_table': 'evidence_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChainOfCustodyLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATED', 'Evidence Created / Notice Issued'), ('FILE_UPLOADED', 'Binary File Uploaded'), ('HASH_VERIFIED', 'Cryptographic SHA-256 Hash Verified'), ('ACCESSED', 'Evidence Viewed by Investigator'), ('DOWNLOADED', 'Court Evidence Export Downloaded'), ('SEALED', 'Evidence Vault Sealed for Trial')], default='CREATED', max_length=50)),
                ('performed_by', models.CharField(default='System Automator', max_length=100)),
                ('role', models.CharField(default='Investigator', max_length=50)),
                ('ip_address', models.CharField(default='127.0.0.1', max_length=50)),
                ('details', models.TextField(blank=True)),
                ('hash_snapshot', models.CharField(blank=True, max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('evidence_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_logs', to='complaints.evidenceitem')),
            ],
            options={
                'db_table': 'evidence_custody_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
